"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpConst = void 0;
var HttpConst;
(function (HttpConst) {
    let CSPD;
    (function (CSPD) {
        CSPD["BASE_URI"] = "base-uri";
        CSPD["BLOCK_ALL_MIXED_CONTENT"] = "block-all-mixed-content";
        CSPD["CHILD_SRC"] = "child-src";
        CSPD["CONNECT_SRC"] = "connect-src";
        CSPD["DEFAULT_SRC"] = "default-src";
        CSPD["FONT_SRC"] = "font-src";
        CSPD["FORM_ACTION"] = "form-action";
        CSPD["FRAME_ANCESTORS"] = "frame-ancestors";
        CSPD["FRAME_SRC"] = "frame-src";
        CSPD["IMG_SRC"] = "img-src";
        CSPD["MANIFEST_SRC"] = "manifest-src";
        CSPD["MEDIA_SRC"] = "media-src";
        CSPD["OBJECT_SRC"] = "object-src";
        CSPD["PLUGIN_TYPES"] = "plugin-types";
        CSPD["REFERRER"] = "referrer";
        CSPD["REPORT_URI"] = "report-uri";
        CSPD["REQUIRE_SRI_FOR"] = "require-sri-for";
        CSPD["PREFETCH_SRC"] = "prefetch-src";
        CSPD["SANDBOX"] = "sandbox";
        CSPD["SCRIPT_SRC"] = "script-src";
        CSPD["STYLE_SRC"] = "style-src";
        CSPD["UPGRADE_INSECURE_REQUESTS"] = "upgrade-insecure-requests";
        CSPD["WORKER_SRC"] = "worker-src";
    })(CSPD = HttpConst.CSPD || (HttpConst.CSPD = {}));
    ;
    let CSPS;
    (function (CSPS) {
        CSPS["SELF"] = "self";
        CSPS["NONE"] = "none";
        CSPS["STRICT_DYNAMIC"] = "strict-dynamic";
        CSPS["UNSAFE_INLINE"] = "unsafe-inline";
        CSPS["UNSAFE_EVAL"] = "unsafe-eval";
        CSPS["SELF_QTD"] = "'self'";
        CSPS["NONE_QTD"] = "'none'";
        CSPS["STRICT_DYNAMIC_QTD"] = "'strict-dynamic'";
        CSPS["UNSAFE_INLINE_QTD"] = "'unsafe-inline'";
        CSPS["UNSAFE_EVAL_QTD"] = "'unsafe-eval'";
    })(CSPS = HttpConst.CSPS || (HttpConst.CSPS = {}));
    ;
    let CacheControls;
    (function (CacheControls) {
        CacheControls["IMMUTABLE"] = "immutable";
        CacheControls["MAX_AGE"] = "max-age";
        CacheControls["MAX_STALE"] = "max-stale";
        CacheControls["MIN_FRESH"] = "min-fresh";
        CacheControls["MUST_REVALIDATE"] = "must-revalidate";
        CacheControls["NO_CACHE"] = "no-cache";
        CacheControls["NO_STORE"] = "no-store";
        CacheControls["NO_TRANSFORM"] = "no-transform";
        CacheControls["ONLY_IF_CACHED"] = "only-if-cached";
        CacheControls["PRIVATE"] = "private";
        CacheControls["PROXY_REVALIDATE"] = "proxy-revalidate";
        CacheControls["PUBLIC"] = "public";
        CacheControls["S_MAXAGE"] = "s-maxage";
        CacheControls["STALE_IF_ERROR"] = "stale-if-error";
        CacheControls["STALE_WHILE_REVALIDATE"] = "stale-while-revalidate";
    })(CacheControls = HttpConst.CacheControls || (HttpConst.CacheControls = {}));
    ;
    let ResponseCodes;
    (function (ResponseCodes) {
        ResponseCodes[ResponseCodes["CONTINUE"] = 100] = "CONTINUE";
        ResponseCodes[ResponseCodes["SWITCHING_PROTOCOL"] = 101] = "SWITCHING_PROTOCOL";
        ResponseCodes[ResponseCodes["PROCESSING"] = 102] = "PROCESSING";
        ResponseCodes[ResponseCodes["EARLY_HINTS"] = 103] = "EARLY_HINTS";
        ResponseCodes[ResponseCodes["OK"] = 200] = "OK";
        ResponseCodes[ResponseCodes["CREATED"] = 201] = "CREATED";
        ResponseCodes[ResponseCodes["ACCEPTED"] = 202] = "ACCEPTED";
        ResponseCodes[ResponseCodes["NON_AUTHORITATIVE_INFORMATION"] = 203] = "NON_AUTHORITATIVE_INFORMATION";
        ResponseCodes[ResponseCodes["NO_CONTENT"] = 204] = "NO_CONTENT";
        ResponseCodes[ResponseCodes["RESET_CONTENT"] = 205] = "RESET_CONTENT";
        ResponseCodes[ResponseCodes["PARTIAL_CONTENT"] = 206] = "PARTIAL_CONTENT";
        ResponseCodes[ResponseCodes["MULTI_STATUS"] = 207] = "MULTI_STATUS";
        ResponseCodes[ResponseCodes["ALREADY_REPORTED"] = 208] = "ALREADY_REPORTED";
        ResponseCodes[ResponseCodes["IM_USED"] = 226] = "IM_USED";
        ResponseCodes[ResponseCodes["MULTIPLE_CHOICE"] = 300] = "MULTIPLE_CHOICE";
        ResponseCodes[ResponseCodes["MOVED_PERMANENTLY"] = 301] = "MOVED_PERMANENTLY";
        ResponseCodes[ResponseCodes["MOVED_TEMPORARILY"] = 302] = "MOVED_TEMPORARILY";
        ResponseCodes[ResponseCodes["FOUND"] = 302] = "FOUND";
        ResponseCodes[ResponseCodes["SEE_OTHER"] = 303] = "SEE_OTHER";
        ResponseCodes[ResponseCodes["NOT_MODIFIED"] = 304] = "NOT_MODIFIED";
        ResponseCodes[ResponseCodes["USE_PROXY"] = 305] = "USE_PROXY";
        ResponseCodes[ResponseCodes["TEMPORARY_REDIRECT"] = 307] = "TEMPORARY_REDIRECT";
        ResponseCodes[ResponseCodes["PERMANENT_REDIRECT"] = 308] = "PERMANENT_REDIRECT";
        ResponseCodes[ResponseCodes["BAD_REQUEST"] = 400] = "BAD_REQUEST";
        ResponseCodes[ResponseCodes["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
        ResponseCodes[ResponseCodes["PAYMENT_REQUIRED"] = 402] = "PAYMENT_REQUIRED";
        ResponseCodes[ResponseCodes["FORBIDDEN"] = 403] = "FORBIDDEN";
        ResponseCodes[ResponseCodes["NOT_FOUND"] = 404] = "NOT_FOUND";
        ResponseCodes[ResponseCodes["METHOD_NOT_ALLOWED"] = 405] = "METHOD_NOT_ALLOWED";
        ResponseCodes[ResponseCodes["NOT_ACCEPTABLE"] = 406] = "NOT_ACCEPTABLE";
        ResponseCodes[ResponseCodes["PROXY_AUTHENTICATION_REQUIRED"] = 407] = "PROXY_AUTHENTICATION_REQUIRED";
        ResponseCodes[ResponseCodes["REQUEST_TIMEOUT"] = 408] = "REQUEST_TIMEOUT";
        ResponseCodes[ResponseCodes["CONFLICT"] = 409] = "CONFLICT";
        ResponseCodes[ResponseCodes["GONE"] = 410] = "GONE";
        ResponseCodes[ResponseCodes["LENGTH_REQUIRED"] = 411] = "LENGTH_REQUIRED";
        ResponseCodes[ResponseCodes["PRECONDITION_FAILED"] = 412] = "PRECONDITION_FAILED";
        ResponseCodes[ResponseCodes["PAYLOAD_TOO_LARGE"] = 413] = "PAYLOAD_TOO_LARGE";
        ResponseCodes[ResponseCodes["URI_TOO_LONG"] = 414] = "URI_TOO_LONG";
        ResponseCodes[ResponseCodes["UNSUPPORTED_MEDIA_TYPE"] = 415] = "UNSUPPORTED_MEDIA_TYPE";
        ResponseCodes[ResponseCodes["RANGE_NOT_SATISFIABLE"] = 416] = "RANGE_NOT_SATISFIABLE";
        ResponseCodes[ResponseCodes["EXPECTATION_FAILED"] = 417] = "EXPECTATION_FAILED";
        ResponseCodes[ResponseCodes["I_AM_A_TEAPOT"] = 418] = "I_AM_A_TEAPOT";
        ResponseCodes[ResponseCodes["MISDIRECTED_REQUEST"] = 421] = "MISDIRECTED_REQUEST";
        ResponseCodes[ResponseCodes["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY";
        ResponseCodes[ResponseCodes["LOCKED"] = 423] = "LOCKED";
        ResponseCodes[ResponseCodes["FAILED_DEPENDENCY"] = 424] = "FAILED_DEPENDENCY";
        ResponseCodes[ResponseCodes["UPGRADE_REQUIRED"] = 426] = "UPGRADE_REQUIRED";
        ResponseCodes[ResponseCodes["PRECONDITION_REQUIRED"] = 428] = "PRECONDITION_REQUIRED";
        ResponseCodes[ResponseCodes["TOO_MANY_REQUESTS"] = 429] = "TOO_MANY_REQUESTS";
        ResponseCodes[ResponseCodes["REQUEST_HEADER_FIELDS_TOO_LARGE"] = 431] = "REQUEST_HEADER_FIELDS_TOO_LARGE";
        ResponseCodes[ResponseCodes["REQUESTED_HOST_UNAVAILABLE"] = 434] = "REQUESTED_HOST_UNAVAILABLE";
        ResponseCodes[ResponseCodes["RETRY_WITH"] = 449] = "RETRY_WITH";
        ResponseCodes[ResponseCodes["UNAVAILABLE_FOR_LEGAL_REASONS"] = 451] = "UNAVAILABLE_FOR_LEGAL_REASONS";
        ResponseCodes[ResponseCodes["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
        ResponseCodes[ResponseCodes["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED";
        ResponseCodes[ResponseCodes["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
        ResponseCodes[ResponseCodes["SERVICE_UNAVAILABLE"] = 503] = "SERVICE_UNAVAILABLE";
        ResponseCodes[ResponseCodes["GATEWAY_TIMEOUT"] = 504] = "GATEWAY_TIMEOUT";
        ResponseCodes[ResponseCodes["HTTP_VERSION_NOT_SUPPORTED"] = 505] = "HTTP_VERSION_NOT_SUPPORTED";
        ResponseCodes[ResponseCodes["VARIANT_ALSO_NEGOTIATES"] = 506] = "VARIANT_ALSO_NEGOTIATES";
        ResponseCodes[ResponseCodes["INSUFFICIENT_STORAGE"] = 507] = "INSUFFICIENT_STORAGE";
        ResponseCodes[ResponseCodes["LOOP_DETECTED"] = 508] = "LOOP_DETECTED";
        ResponseCodes[ResponseCodes["BANDWIDTH_LIMIT_EXCEEDED"] = 509] = "BANDWIDTH_LIMIT_EXCEEDED";
        ResponseCodes[ResponseCodes["NOT_EXTENDED"] = 510] = "NOT_EXTENDED";
        ResponseCodes[ResponseCodes["NETWORK_AUTHENTICATION_REQUIRED"] = 511] = "NETWORK_AUTHENTICATION_REQUIRED";
        ResponseCodes[ResponseCodes["UNKNOWN_ERROR"] = 520] = "UNKNOWN_ERROR";
        ResponseCodes[ResponseCodes["WEB_SERVER_IS_DOWN"] = 521] = "WEB_SERVER_IS_DOWN";
        ResponseCodes[ResponseCodes["CONNECTION_TIMED_OUT"] = 522] = "CONNECTION_TIMED_OUT";
        ResponseCodes[ResponseCodes["ORIGIN_IS_UNREACHABLE"] = 523] = "ORIGIN_IS_UNREACHABLE";
        ResponseCodes[ResponseCodes["A_TIMEOUT_OCCURRED"] = 524] = "A_TIMEOUT_OCCURRED";
        ResponseCodes[ResponseCodes["SSL_HANDSHAKE_FAILED"] = 525] = "SSL_HANDSHAKE_FAILED";
        ResponseCodes[ResponseCodes["INVALID_SSL_CERTIFICATE"] = 526] = "INVALID_SSL_CERTIFICATE";
    })(ResponseCodes = HttpConst.ResponseCodes || (HttpConst.ResponseCodes = {}));
    ;
    let Methods;
    (function (Methods) {
        Methods["CONNECT"] = "CONNECT";
        Methods["COPY"] = "COPY";
        Methods["DELETE"] = "DELETE";
        Methods["GET"] = "GET";
        Methods["HEAD"] = "HEAD";
        Methods["LINK"] = "LINK";
        Methods["LOCK"] = "LOCK";
        Methods["OPTIONS"] = "OPTIONS";
        Methods["PATCH"] = "PATCH";
        Methods["POST"] = "POST";
        Methods["PROPFIND"] = "PROPFIND";
        Methods["PURGE"] = "PURGE";
        Methods["PUT"] = "PUT";
        Methods["TRACE"] = "TRACE";
        Methods["UNLINK"] = "UNLINK";
        Methods["UNLOCK"] = "UNLOCK";
        Methods["VIEW"] = "VIEW";
    })(Methods = HttpConst.Methods || (HttpConst.Methods = {}));
    let Headers;
    (function (Headers) {
        Headers["A_IM"] = "A-IM";
        Headers["ACCEPT"] = "Accept";
        Headers["ACCEPT_CH"] = "Accept-CH";
        Headers["ACCEPT_CH_LIFETIME"] = "Accept-CH-Lifetime";
        Headers["ACCEPT_CHARSET"] = "Accept-Charset";
        Headers["ACCEPT_DATETIME"] = "Accept-Datetime";
        Headers["ACCEPT_ENCODING"] = "Accept-Encoding";
        Headers["ACCEPT_LANGUAGE"] = "Accept-Language";
        Headers["ACCEPT_PATCH"] = "Accept-Patch";
        Headers["ACCEPT_RANGES"] = "Accept-Ranges";
        Headers["ACCESS_CONTROL_ALLOW_CREDENTIALS"] = "Access-Control-Allow-Credentials";
        Headers["ACCESS_CONTROL_ALLOW_HEADERS"] = "Access-Control-Allow-Headers";
        Headers["ACCESS_CONTROL_ALLOW_METHODS"] = "Access-Control-Allow-Methods";
        Headers["ACCESS_CONTROL_ALLOW_ORIGIN"] = "Access-Control-Allow-Origin";
        Headers["ACCESS_CONTROL_EXPOSE_HEADERS"] = "Access-Control-Expose-Headers";
        Headers["ACCESS_CONTROL_MAX_AGE"] = "Access-Control-Max-Age";
        Headers["ACCESS_CONTROL_REQUEST_HEADERS"] = "Access-Control-Request-Headers";
        Headers["ACCESS_CONTROL_REQUEST_METHOD"] = "Access-Control-Request-Method";
        Headers["AGE"] = "Age";
        Headers["ALLOW"] = "Allow";
        Headers["ALT_SVC"] = "Alt-Svc";
        Headers["ALTERNATES"] = "Alternates";
        Headers["AUTHORIZATION"] = "Authorization";
        Headers["CACHE_CONTROL"] = "Cache-Control";
        Headers["CONNECTION"] = "Connection";
        Headers["CONTENT_DISPOSITION"] = "Content-Disposition";
        Headers["CONTENT_DPR"] = "Content-DPR";
        Headers["CONTENT_ENCODING"] = "Content-Encoding";
        Headers["CONTENT_LANGUAGE"] = "Content-Language";
        Headers["CONTENT_LENGTH"] = "Content-Length";
        Headers["CONTENT_LOCATION"] = "Content-Location";
        Headers["CONTENT_MD5"] = "Content-MD5";
        Headers["CONTENT_RANGE"] = "Content-Range";
        Headers["CONTENT_SECURITY_POLICY"] = "Content-Security-Policy";
        Headers["CONTENT_SECURITY_POLICY_REPORT_ONLY"] = "Content-Security-Policy-Report-Only";
        Headers["CONTENT_TYPE"] = "Content-Type";
        Headers["CONTENT_VERSION"] = "Content-Version";
        Headers["COOKIE"] = "Cookie";
        Headers["DATE"] = "Date";
        Headers["DELTA_BASE"] = "Delta-Base";
        Headers["DERIVED_FROM"] = "Derived-From";
        Headers["DNT"] = "DNT";
        Headers["DOWNLINK"] = "Downlink";
        Headers["DPR"] = "DPR";
        Headers["EARLY_DATA"] = "Early-Data";
        Headers["ETAG"] = "ETag";
        Headers["EXPECT"] = "Expect";
        Headers["EXPECT_CT"] = "Expect-CT";
        Headers["EXPIRES"] = "Expires";
        Headers["FORWARDED"] = "Forwarded";
        Headers["FROM"] = "From";
        Headers["FRONT_END_HTTPS"] = "Front-End-Https";
        Headers["HOST"] = "Host";
        Headers["IF_MATCH"] = "If-Match";
        Headers["IF_MODIFIED_SINCE"] = "If-Modified-Since";
        Headers["IF_NONE_MATCH"] = "If-None-Match";
        Headers["IF_RANGE"] = "If-Range";
        Headers["IF_UNMODIFIED_SINCE"] = "If-Unmodified-Since";
        Headers["IM"] = "IM";
        Headers["KEEP_ALIVE"] = "Keep-Alive";
        Headers["LARGE_ALLOCATION"] = "Large-Allocation";
        Headers["LAST_EVENT_ID"] = "Last-Event-ID";
        Headers["LAST_MODIFIED"] = "Last-Modified";
        Headers["LINK"] = "Link";
        Headers["LOCATION"] = "Location";
        Headers["MAX_FORWARDS"] = "Max-Forwards";
        Headers["MIME_VERSION"] = "MIME-Version";
        Headers["ORIGIN"] = "Origin";
        Headers["P3P"] = "P3P";
        Headers["PING_FROM"] = "Ping-From";
        Headers["PING_TO"] = "Ping-To";
        Headers["PRAGMA"] = "Pragma";
        Headers["PROXY_AUTHENTICATE"] = "Proxy-Authenticate";
        Headers["PROXY_AUTHORIZATION"] = "Proxy-Authorization";
        Headers["PROXY_CONNECTION"] = "Proxy-Connection";
        Headers["PUBLIC"] = "Public";
        Headers["PUBLIC_KEY_PINS"] = "Public-Key-Pins";
        Headers["PUBLIC_KEY_PINS_REPORT_ONLY"] = "Public-Key-Pins-Report-Only";
        Headers["RANGE"] = "Range";
        Headers["REFERER"] = "Referer";
        Headers["REFERRER_POLICY"] = "Referrer-Policy";
        Headers["REFRESH"] = "Refresh";
        Headers["RETRY_AFTER"] = "Retry-After";
        Headers["SAVE_DATA"] = "Save-Data";
        Headers["SEC_WEBSOCKET_ACCEPT"] = "Sec-WebSocket-Accept";
        Headers["SEC_WEBSOCKET_EXTENSIONS"] = "Sec-WebSocket-Extensions";
        Headers["SEC_WEBSOCKET_KEY"] = "Sec-WebSocket-Key";
        Headers["SEC_WEBSOCKET_PROTOCOL"] = "Sec-WebSocket-Protocol";
        Headers["SEC_WEBSOCKET_VERSION"] = "Sec-WebSocket-Version";
        Headers["SERVER"] = "Server";
        Headers["SERVER_TIMING"] = "Server-Timing";
        Headers["SET_COOKIE"] = "Set-Cookie";
        Headers["SOURCEMAP"] = "SourceMap";
        Headers["STATUS"] = "Status";
        Headers["STRICT_TRANSPORT_SECURITY"] = "Strict-Transport-Security";
        Headers["TE"] = "TE";
        Headers["TIMING_ALLOW_ORIGIN"] = "Timing-Allow-Origin";
        Headers["TITLE"] = "Title";
        Headers["TK"] = "Tk";
        Headers["TRAILER"] = "Trailer";
        Headers["TRANSFER_ENCODING"] = "Transfer-Encoding";
        Headers["UPGRADE"] = "Upgrade";
        Headers["UPGRADE_INSECURE_REQUESTS"] = "Upgrade-Insecure-Requests";
        Headers["USER_AGENT"] = "User-Agent";
        Headers["VARY"] = "Vary";
        Headers["VIA"] = "Via";
        Headers["VIEWPORT_WIDTH"] = "Viewport-Width";
        Headers["WARNING"] = "Warning";
        Headers["WIDTH"] = "Width";
        Headers["WWW_AUTHENTICATE"] = "WWW-Authenticate";
        Headers["X_ATT_DEVICEID"] = "X-ATT-DeviceId";
        Headers["X_CONTENT_DURATION"] = "X-Content-Duration";
        Headers["X_CONTENT_SECURITY_POLICY"] = "X-Content-Security-Policy";
        Headers["X_CONTENT_TYPE_OPTIONS"] = "X-Content-Type-Options";
        Headers["X_CORRELATION_ID"] = "X-Correlation-ID";
        Headers["X_CSRF_TOKEN"] = "X-Csrf-Token";
        Headers["X_DNS_PREFETCH_CONTROL"] = "X-DNS-Prefetch-Control";
        Headers["X_DOWNLOAD_OPTIONS"] = "X-Download-Options";
        Headers["X_FORWARDED_FOR"] = "X-Forwarded-For";
        Headers["X_FORWARDED_HOST"] = "X-Forwarded-Host";
        Headers["X_FORWARDED_PROTO"] = "X-Forwarded-Proto";
        Headers["X_FRAME_OPTIONS"] = "X-Frame-Options";
        Headers["X_HTTP_METHOD_OVERRIDE"] = "X-Http-Method-Override";
        Headers["X_PERMITTED_CROSS_DOMAIN_POLICIES"] = "X-Permitted-Cross-Domain-Policies";
        Headers["X_POWERED_BY"] = "X-Powered-By";
        Headers["X_REQUEST_ID"] = "X-Request-ID";
        Headers["X_REQUESTED_WITH"] = "X-Requested-With";
        Headers["X_ROBOTS_TAG"] = "X-Robots-Tag";
        Headers["X_UA_COMPATIBLE"] = "X-UA-Compatible";
        Headers["X_UIDH"] = "X-UIDH";
        Headers["X_WAP_PROFILE"] = "X-Wap-Profile";
        Headers["X_WEBKIT_CSP"] = "X-WebKit-CSP";
        Headers["X_XSS_PROTECTION"] = "X-XSS-Protection";
    })(Headers = HttpConst.Headers || (HttpConst.Headers = {}));
    ;
    let ContentEncodings;
    (function (ContentEncodings) {
        ContentEncodings["AES128GCM"] = "aes128gcm";
        ContentEncodings["BR"] = "br";
        ContentEncodings["COMPRESS"] = "compress";
        ContentEncodings["DEFLATE"] = "deflate";
        ContentEncodings["EXI"] = "exi";
        ContentEncodings["GZIP"] = "gzip";
        ContentEncodings["IDENTITY"] = "identity";
        ContentEncodings["PACK200_GZIP"] = "pack200-gzip";
        ContentEncodings["SDCH"] = "sdch";
        ContentEncodings["X_COMPRESS"] = "x-compress";
        ContentEncodings["X_GZIP"] = "x-gzip";
    })(ContentEncodings = HttpConst.ContentEncodings || (HttpConst.ContentEncodings = {}));
    ;
    let TrackingStatuses;
    (function (TrackingStatuses) {
        TrackingStatuses["UNDER_CONSTRUCTION"] = "!";
        TrackingStatuses["DYNAMIC"] = "?";
        TrackingStatuses["GATEWAY"] = "G";
        TrackingStatuses["NOT_TRACKING"] = "N";
        TrackingStatuses["TRACKING"] = "T";
        TrackingStatuses["TRACKING_WITH_CONSENT"] = "C";
        TrackingStatuses["TRACKING_ONLY_IF_CONSENT"] = "P";
        TrackingStatuses["DISREGARDING_DNT"] = "D";
        TrackingStatuses["UPDATED"] = "U";
    })(TrackingStatuses = HttpConst.TrackingStatuses || (HttpConst.TrackingStatuses = {}));
    ;
    let MimeTypes;
    (function (MimeTypes) {
        MimeTypes["APPLICATION_ATOM_XML"] = "application/atom+xml";
        MimeTypes["APPLICATION_EDI_X12"] = "application/EDI-X12";
        MimeTypes["APPLICATION_EDIFACT"] = "application/EDIFACT";
        MimeTypes["APPLICATION_JSON"] = "application/json";
        MimeTypes["APPLICATION_JAVASCRIPT"] = "application/javascript";
        MimeTypes["APPLICATION_OCTET_STREAM"] = "application/octet-stream";
        MimeTypes["APPLICATION_OGG"] = "application/ogg";
        MimeTypes["APPLICATION_PDF"] = "application/pdf";
        MimeTypes["APPLICATION_POSTSCRIPT"] = "application/postscript";
        MimeTypes["APPLICATION_SOAP_XML"] = "application/soap+xml";
        MimeTypes["APPLICATION_FONT_WOFF"] = "application/font-woff";
        MimeTypes["APPLICATION_XHTML_XML"] = "application/xhtml+xml";
        MimeTypes["APPLICATION_XML_DTD"] = "application/xml-dtd";
        MimeTypes["APPLICATION_XOP_XML"] = "application/xop+xml";
        MimeTypes["APPLICATION_ZIP"] = "application/zip";
        MimeTypes["APPLICATION_GZIP"] = "application/gzip";
        MimeTypes["APPLICATION_X_BITTORRENT"] = "application/x-bittorrent";
        MimeTypes["APPLICATION_X_TEX"] = "application/x-tex";
        MimeTypes["APPLICATION_XML"] = "application/xml";
        MimeTypes["APPLICATION_X_WWW_FORM_URLENCODED"] = "application/x-www-form-urlencoded";
        MimeTypes["APPLICATION_X_DVI"] = "application/x-dvi";
        MimeTypes["APPLICATION_X_LATEX"] = "application/x-latex";
        MimeTypes["APPLICATION_X_FONT_TTF"] = "application/x-font-ttf";
        MimeTypes["APPLICATION_X_SHOCKWAVE_FLASH"] = "application/x-shockwave-flash";
        MimeTypes["APPLICATION_X_STUFFIT"] = "application/x-stuffit";
        MimeTypes["APPLICATION_X_RAR_COMPRESSED"] = "application/x-rar-compressed";
        MimeTypes["APPLICATION_X_TAR"] = "application/x-tar";
        MimeTypes["APPLICATION_X_JQUERY_TMPL"] = "application/x-jquery-tmpl";
        MimeTypes["APPLICATION_X_JAVASCRIPT"] = "application/x-javascript";
        MimeTypes["APPLICATION_PKCDS12"] = "application/x-pkcs12";
        MimeTypes["APPLICATION_PKCDS7_CERTIFICATES"] = "application/x-pkcs7-certificates";
        MimeTypes["APPLICATION_PKCDS7_CERTREQRESP"] = "application/x-pkcs7-certreqresp";
        MimeTypes["APPLICATION_PKCDS7_MIME"] = "application/x-pkcs7-mime";
        MimeTypes["APPLICATION_PKCDS7_SIGNATURE"] = "application/x-pkcs7-signature";
        MimeTypes["AUDIO_BASIC"] = "audio/basic";
        MimeTypes["AUDIO_L24"] = "audio/L24";
        MimeTypes["AUDIO_MP4"] = "audio/mp4";
        MimeTypes["AUDIO_AAC"] = "audio/aac";
        MimeTypes["AUDIO_MPEG"] = "audio/mpeg";
        MimeTypes["AUDIO_OGG"] = "audio/ogg";
        MimeTypes["AUDIO_VORBIS"] = "audio/vorbis";
        MimeTypes["AUDIO_X_MS_WMA"] = "audio/x-ms-wma";
        MimeTypes["AUDIO_X_MS_WAX"] = "audio/x-ms-wax";
        MimeTypes["AUDIO_VND_RN_REALAUDIO"] = "audio/vnd.rn-realaudio";
        MimeTypes["AUDIO_VND_WAVE"] = "audio/vnd.wave";
        MimeTypes["AUDIO_WEBM"] = "audio/webm";
        MimeTypes["IMAGE_GIF"] = "image/gif";
        MimeTypes["IMAGE_JPEG"] = "image/jpeg";
        MimeTypes["IMAGE_PJPEG"] = "image/pjpeg";
        MimeTypes["IMAGE_PNG"] = "image/png";
        MimeTypes["IMAGE_SVG_XML"] = "image/svg+xml";
        MimeTypes["IMAGE_TIFF"] = "image/tiff";
        MimeTypes["IMAGE_VND_MICROSOFT_ICON"] = "image/vnd.microsoft.icon";
        MimeTypes["IMAGE_VND_WAP_WBMP"] = "image/vnd.wap.wbmp";
        MimeTypes["IMAGE_WEBP"] = "image/webp";
        MimeTypes["IMAGE_HTTP"] = "message/http";
        MimeTypes["IMAGE_IMDN_XML"] = "message/imdn+xml";
        MimeTypes["IMAGE_PARTIAL"] = "message/partial";
        MimeTypes["IMAGE_RFC822"] = "message/rfc822";
        MimeTypes["IMAGE_EXAMPLE"] = "model/example";
        MimeTypes["IMAGE_IGES"] = "model/iges";
        MimeTypes["IMAGE_MESH"] = "model/mesh";
        MimeTypes["IMAGE_VRML"] = "model/vrml";
        MimeTypes["IMAGE_X3D_BINARY"] = "model/x3d+binary";
        MimeTypes["IMAGE_X3D_VRML"] = "model/x3d+vrml";
        MimeTypes["IMAGE_X3D_XML"] = "model/x3d+xml";
        MimeTypes["IMAGE_MIXED"] = "multipart/mixed";
        MimeTypes["IMAGE_ALTERNATIVE"] = "multipart/alternative";
        MimeTypes["IMAGE_RELATED"] = "multipart/related";
        MimeTypes["IMAGE_FORM_DATA"] = "multipart/form-data";
        MimeTypes["IMAGE_SIGNED"] = "multipart/signed";
        MimeTypes["IMAGE_ENCRYPTED"] = "multipart/encrypted";
        MimeTypes["IMAGE_CMD"] = "text/cmd";
        MimeTypes["IMAGE_CSS"] = "text/css";
        MimeTypes["IMAGE_CSV"] = "text/csv";
        MimeTypes["IMAGE_HTML"] = "text/html";
        MimeTypes["IMAGE_JAVASCRIPT"] = "text/javascript";
        MimeTypes["IMAGE_PLAIN"] = "text/plain";
        MimeTypes["IMAGE_PHP"] = "text/php";
        MimeTypes["IMAGE_XML"] = "text/xml";
        MimeTypes["IMAGE_MARKDOWN"] = "text/markdown";
        MimeTypes["IMAGE_CACHE_MANIFEST"] = "text/cache-manifest";
        MimeTypes["IMAGE_MPEG"] = "video/mpeg";
        MimeTypes["IMAGE_MP4"] = "video/mp4";
        MimeTypes["IMAGE_OGG"] = "video/ogg";
        MimeTypes["IMAGE_QUICKTIME"] = "video/quicktime";
        MimeTypes["IMAGE_WEBM"] = "video/webm";
        MimeTypes["IMAGE_X_MS_WMV"] = "video/x-ms-wmv";
        MimeTypes["IMAGE_X_FLV"] = "video/x-flv";
        MimeTypes["IMAGE__3GPP"] = "video/3gpp";
        MimeTypes["IMAGE__3GPP2"] = "video/3gpp2";
        MimeTypes["APPLICATION_VND_OD_TEXT"] = "application/vnd.oasis.opendocument.text";
        MimeTypes["APPLICATION_VND_OD_SPERADSHEET"] = "application/vnd.oasis.opendocument.spreadsheet";
        MimeTypes["APPLICATION_VND_OD_PRESENTATION"] = "application/vnd.oasis.opendocument.presentation";
        MimeTypes["APPLICATION_VND_OD_GRAPHICS"] = "application/vnd.oasis.opendocument.graphics";
        MimeTypes["APPLICATION_MS_EXCEL"] = "application/vnd.ms-excel";
        MimeTypes["APPLICATION_MS_EXCEL_2007"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        MimeTypes["APPLICATION_MS_POWERPOINT"] = "application/vnd.ms-powerpoint";
        MimeTypes["APPLICATION_MS_POWERPOINT_2007"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        MimeTypes["APPLICATION_MS_WORD_2007"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        MimeTypes["APPLICATION_MS_WORD"] = "application/msword";
        MimeTypes["APPLICATION_XUL"] = "application/vnd.mozilla.xul+xml";
        MimeTypes["APPLICATION_KML"] = "application/vnd.google-earth.kml+xml";
    })(MimeTypes = HttpConst.MimeTypes || (HttpConst.MimeTypes = {}));
    ;
})(HttpConst = exports.HttpConst || (exports.HttpConst = {}));
